#!/usr/bin/env php
<?php

use Illuminate\Foundation\Application;
use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

// Point Composer to the shared vendor directory
$vendorPath = dirname(__DIR__, 2).'/vendor';
putenv('COMPOSER_VENDOR_DIR='.$vendorPath);
$_ENV['COMPOSER_VENDOR_DIR'] = $vendorPath;
$_SERVER['COMPOSER_VENDOR_DIR'] = $vendorPath;

require __DIR__.'/../../vendor/autoload.php';

/** @var Application $app */
$app = require_once __DIR__.'/bootstrap/app.php';

exit($app->handleCommand(new ArgvInput));
